export const themeAssets = {
  logoMain: '/assets/loc/logo-main.webp',
  logoAlt: '/assets/loc/logo-alt.webp',
  moonMedallion: '/assets/loc/moon-medallion.webp',
  heroMoon: '/assets/loc/hero-full-moon.webp',
  heroWorld: '/assets/loc/hero-castle-carnival.webp',
  ferrisWheel: '/assets/loc/ferris-wheel.webp',
  tents: '/assets/loc/tents-upper.webp',
  waterReflection: '/assets/loc/water-reflection.webp',
  celestialChain: '/assets/loc/celestial-chain-banner.webp',
  crowStanding: '/assets/loc/crow-standing.webp',
  crowOnBooks: '/assets/loc/crow-on-books.webp',
  bookStack: '/assets/loc/book-stack-large.webp',
  openGrimoire: '/assets/loc/open-grimoire.webp',
  tarotSet: '/assets/loc/tarot-polaroid-set.webp',
  waxSeal: '/assets/loc/wax-seal.webp',
  lanternsTop: '/assets/loc/lantern-row-top.webp',
  charms: '/assets/loc/charms-right.webp',
  crystalClusters: '/assets/loc/crystal-clusters.webp',
  floralVines: '/assets/loc/floral-vines.webp',
  wisteriaVines: '/assets/loc/wisteria-vines.webp',
  candles: '/assets/loc/candles.webp',
  floralBorder: '/assets/loc/floral-celestial-border.webp',
  ornateBorders: '/assets/loc/ornate-border-strips.webp',
  noteRealLife: '/assets/loc/paper-note-real-life.webp',
  noteMessMagic: '/assets/loc/paper-note-mess-magic.webp',
  noteMoments: '/assets/loc/paper-note-moments.webp',
  checklist: '/assets/loc/paper-checklist.webp',
  ticket: '/assets/loc/admit-one-ticket.webp',
  paperCards: '/assets/loc/paper-card-set.webp',
  navBar: '/assets/loc/nav-bar.webp',
  categoryIcons: '/assets/loc/category-icons-row.webp',
  categoryCards: '/assets/loc/category-cards-row.webp',
  candleLantern: '/assets/loc/candle-lantern-cluster.webp',
  bookStackCrystal: '/assets/loc/book-stack-crystal.webp',
  boats: '/assets/loc/boats.webp',
  latestLife: '/assets/loc/latest-card-life.webp',
  latestCreative: '/assets/loc/latest-card-creative.webp',
  latestReviews: '/assets/loc/latest-card-reviews.webp',
  latestHeading: '/assets/loc/latest-heading.webp',
  viewAllButton: '/assets/loc/view-all-button.webp',
  aboutCard: '/assets/loc/about-card.webp',
  aboutPolaroid: '/assets/loc/about-polaroid.webp',
  aboutBookMug: '/assets/loc/about-book-mug.webp',
} as const

export type ThemeAssetKey = keyof typeof themeAssets
