import { useState, useEffect } from 'react'
import { supabase } from '@/integrations/supabase/client'
import type { Database } from '@/integrations/supabase/types'
import { Button } from '@/components/ui/button'
import { Plus, Trash2, Save, ChevronUp, ChevronDown, Upload } from 'lucide-react'

type Tables=Database['public']['Tables']
export function AdminPage({title,description,children,action}:{title:string,description?:string,children:React.ReactNode,action?:React.ReactNode}){return <div className="admin-content"><div className="admin-page-heading"><div><span className="admin-eyebrow">LAUREL'S ORGANIZED CHAOS / EDITOR</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>{children}</div>}
export function useTable<T extends keyof Tables>(table:T){const [rows,setRows]=useState<Tables[T]['Row'][]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');async function refresh(){const result=await supabase.from(table).select('*').order('created_at',{ascending:false});setRows((result.data??[]) as unknown as Tables[T]['Row'][]);setError(result.error?.message??'');setLoading(false)}useEffect(()=>{void refresh()},[table]);return {rows,loading,error,refresh}}
export async function uploadImage(file:File){if(!file.type.startsWith('image/')||file.size>10*1024*1024)throw new Error('Choose an image smaller than 10 MB.');const path=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9.-]/g,'-')}`;const {error}=await supabase.storage.from('blog-media').upload(path,file);if(error)throw error;return path}
export function ImageUpload({value,onChange,label='Choose image'}:{value?:string|null,onChange:(path:string)=>void,label?:string}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <div className="upload-control"><label className="upload-label"><Upload size={18}/>{busy?'Uploading...':label}<input type="file" accept="image/*" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{onChange(await uploadImage(file))}catch(err){setError(err instanceof Error?err.message:'Upload failed')}finally{setBusy(false)}}}/></label>{value&&<span className="file-name">{value.split('/').pop()}</span>}{error&&<span role="alert" className="form-error">{error}</span>}</div>}
export function SaveButton({busy=false}: {busy?:boolean}){return <Button type="submit" disabled={busy}><Save size={16}/>{busy?'Saving...':'Save changes'}</Button>}
export function ListEditor<T extends {id:string,sort_order:number,visible:boolean}>({title,rows,fields,onSave,onAdd,onDelete}:{title:string,rows:T[],fields:{key:keyof T,label:string}[],onSave:(row:T)=>Promise<void>,onAdd:()=>Promise<void>,onDelete:(row:T)=>Promise<void>}){const [editing,setEditing]=useState<Record<string,T>>({});const [status,setStatus]=useState('');const sorted=[...rows].sort((a,b)=>a.sort_order-b.sort_order);async function save(row:T){try{await onSave(row);setStatus('Saved.')}catch{setStatus('Could not save.')}}return <section className="admin-section"><div className="admin-section-head"><h2>{title}</h2><Button type="button" variant="outline" onClick={onAdd}><Plus size={16}/> Add item</Button></div>{status&&<p role="status" className="save-status">{status}</p>}<div className="editor-list">{sorted.map((original,i)=>{const row=editing[original.id]??original;return <div className="editor-row" key={row.id}><div className="editor-fields">{fields.map(field=><label key={String(field.key)}>{field.label}<input value={String(row[field.key]??'')} onChange={e=>setEditing({...editing,[row.id]:{...row,[field.key]:e.target.value}})}/></label>)}</div><div className="row-controls"><label className="checkbox-label"><input type="checkbox" checked={row.visible} onChange={e=>{const updated={...row,visible:e.target.checked};setEditing({...editing,[row.id]:updated});void save(updated)}}/> Visible</label><Button type="button" variant="ghost" size="icon" title="Move up" aria-label="Move up" disabled={i===0} onClick={()=>{const neighbor=sorted[i-1];if(neighbor){void save({...row,sort_order:neighbor.sort_order});void save({...neighbor,sort_order:row.sort_order})}}}><ChevronUp/></Button><Button type="button" variant="ghost" size="icon" title="Move down" aria-label="Move down" disabled={i===sorted.length-1} onClick={()=>{const neighbor=sorted[i+1];if(neighbor){void save({...row,sort_order:neighbor.sort_order});void save({...neighbor,sort_order:row.sort_order})}}}><ChevronDown/></Button><Button type="button" variant="outline" onClick={()=>save(row)}><Save size={15}/> Save</Button><Button type="button" variant="ghost" size="icon" title="Delete" aria-label="Delete" onClick={()=>{if(confirm('Delete this item?'))void onDelete(row)}}><Trash2/></Button></div></div>})}</div></section>}