/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OwnerLoginRouteImport } from './routes/owner-login'
import { Route as OwnerSetupRouteImport } from './routes/owner-setup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminPhotosRouteImport } from './routes/admin.photos'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPreviewIdRouteImport } from './routes/admin.preview.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner-login',
  path: '/owner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSetupRoute = OwnerSetupRouteImport.update({
  id: '/owner-setup',
  path: '/owner-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosRoute = AdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewIdRoute = AdminPreviewIdRouteImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/owner-login': typeof OwnerLoginRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/privacy': typeof PrivacyRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/preview/$id': typeof AdminPreviewIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/owner-login': typeof OwnerLoginRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/privacy': typeof PrivacyRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/preview/$id': typeof AdminPreviewIdRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/owner-login': typeof OwnerLoginRoute
  '/owner-setup': typeof OwnerSetupRoute
  '/privacy': typeof PrivacyRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/preview/$id': typeof AdminPreviewIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/owner-login'
    | '/owner-setup'
    | '/privacy'
    | '/admin/about'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/messages'
    | '/admin/photos'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/preview/$id'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/owner-login'
    | '/owner-setup'
    | '/privacy'
    | '/admin/about'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/messages'
    | '/admin/photos'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/preview/$id'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/owner-login'
    | '/owner-setup'
    | '/privacy'
    | '/admin/about'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/messages'
    | '/admin/photos'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/admin/preview/$id'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerSetupRoute: typeof OwnerSetupRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-login': {
      id: '/owner-login'
      path: '/owner-login'
      fullPath: '/owner-login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-setup': {
      id: '/owner-setup'
      path: '/owner-setup'
      fullPath: '/owner-setup'
      preLoaderRoute: typeof OwnerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos': {
      id: '/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AdminPhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview/$id': {
      id: '/admin/preview/$id'
      path: '/preview/$id'
      fullPath: '/admin/preview/$id'
      preLoaderRoute: typeof AdminPreviewIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPhotosRoute: typeof AdminPhotosRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPreviewIdRoute: typeof AdminPreviewIdRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPhotosRoute: AdminPhotosRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPreviewIdRoute: AdminPreviewIdRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerSetupRoute: OwnerSetupRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}